default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *default
  database: kopool_development

test:
  <<: *default
  database: kopool_test

production:
  <<: *default
  database: kopool_production
